### ISSUE TITLE
On click of footer linked icon is not opening proper university url.

### ISSUE THREAD

**Issue by dinesh-07** [Rhythm-cmd/Learn.github.io#10]
I could see the university has its own official LinkedIn profile https://www.linkedin.com/school/sinhgad-college-of-engineering/ better we could link this rather than show an error file on click.

**Comment by dinesh-07** [comment]
[Rhythm Nagre](https://github.com/Rhythm-cmd) can I work on this

**Comment by Rhythm-cmd** [comment]
> [Rhythm Nagre](https://github.com/Rhythm-cmd) can I work on this

Go ahead

**Comment by Rhythm-cmd** [comment]
Add this - https://www.linkedin.com/company/stessaoepune/
