### ISSUE TITLE
Hide dribble icon and expose it later whenever is required

### ISSUE THREAD

**Issue by dinesh-07** [Rhythm-cmd/Learn.github.io#11]
In the footer, we are showing the dribble icon but on click will open the error file. Can't be hidden

**Comment by dinesh-07** [comment]
[Rhythm Nagre](https://github.com/Rhythm-cmd) take a look

**Comment by Rhythm-cmd** [comment]
Work on it

**Comment by dinesh-07** [comment]
Fixed https://github.com/Rhythm-cmd/Learn.github.io/pull/15

**Comment by dinesh-07** [comment]
@Rhythm-cmd please check the updates.
